apiVersion: 1

contactPoints:
  - orgId: 1
    name: rakuten-alerts
    receivers:
      - uid: email-alert-receiver
        type: email
        settings:
          addresses: ${ALERT_EMAIL_TO}
          singleEmail: true
        disableResolveMessage: false
