apiVersion: 1

policies:
  - orgId: 1
    receiver: slack-drift-alerts
    group_by: ["alertname"]
    routes:
      - receiver: slack-drift-alerts
        object_matchers:
          - ["alertname", "=", "Prediction drift (PSI) significant"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
