apiVersion: 1

policies:
  - orgId: 1
    receiver: rakuten-alerts
    group_by: ["alertname"]
    routes:
      - receiver: rakuten-alerts
        object_matchers:
          - ["alertname", "=", "Rakuten prediction drift (PSI)"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
